### PR TITLE
Task Based Text-to-Speech

### PR DESCRIPTION
**Pull request by aritchie**
- This is an async/task based implementation of text-to-speech.  It removes the queuing mechanism since that technically isn't needed anymore.  Cancellation tokens can be used to cancel current speech.  Multiple requests for TTS at one time will simply wait in "queue"
- This has been tested on Android, iOS, & UWP
- This includes a sample project that shows how task based TTS works

### CODE REVIEW

**Comment by aritchie** [comment]
Sorry - my bad on this one.  I ended up adding the samples for testing and fixing some of the issues.  I forgot to merge those in as well.

**Comment by jamesmontemagno** [comment]
Hmmm, will probably need to pull up my changes now and re-do it a bit :( sorry

**Comment by jamesmontemagno** [comment]
I think I have merged in correctly.... in my pr branch

**Comment by jamesmontemagno** [comment]
Can you validate #8 and then i will close this one and squash that one.

**Comment by jamesmontemagno** [comment]
Closing for now and we should work off my cleanup branch. I think Windows Phone is broken though... need to research more.

**Comment by EmilAlipiev** [comment]
Is the Task based available on in 3.0 version? Is there anyway to await / queue speeches if I am running one after another?

**Pull request closed without merging**
