### PR TITLE
iOS: audio route changed handling

### PR DESCRIPTION
**Pull request by nexxuno**
Changes Proposed in this pull request:
-in iOS, when the audio route changes all instances of the speechSynthesizer become obsolete; with this modification we recreate the object each time the audio route chages.

### CODE REVIEW

**Comment by nexxuno** [comment]
@jamesmontemagno I don't know why github sees all those modified lines, if you compare the two files in visual studio it will show you the correct differences that are just a few lines of code.

**Comment by jamesmontemagno** [comment]
Would it be easier to just create a new one each time. This is what we do in essentials: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/TextToSpeech/TextToSpeech.ios.cs#L47

**Comment by nexxuno** [comment]
yes that was my first solution but this looked more optimized... all in all I think you are right it's a bit of an overkill. Resubmitting soon.

**Comment by nexxuno** [comment]
Done, please have a look at it! Thanks.

**Comment by nexxuno** [comment]
@jamesmontemagno hello, do I need to improve this somehow?

**Review by jamesmontemagno — APPROVED** [review]

**Pull request merged**
