### PR TITLE
Tvos plugin

### PR DESCRIPTION
**Pull request by aritchie**
tvOS implementation for 3.0 includes sample

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
@aritchie are you able to update this puppy?

**Comment by aritchie** [comment]
Sure.  What needs to be updated?

**Comment by jamesmontemagno** [comment]
I think there are just some conflicts from the current version that need to be merged in.

**Comment by aritchie** [comment]
I was unable to cherry pick or generate a patch out of this PR due to a whack of errors with possibly the fork being gone for so long.  Anyhow, closing this and opening up a new PR.

**Pull request closed without merging**
